name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: M2 MIAGE
        run: echo "Bonjour tout le monde"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Parcours DLIS
        run: echo "Bonjour les délicieux"
        shell: bash


